name: WF_on_Issues
on:
  issues:
    types: [opened, edited, milestoned]
  workflow_dispatch:
jobs:
  onissue:
    runs-on: ubuntu-latest
    steps: 
      - name: Print github context
        run: |
          echo "${{ github }}"
          echo "${{ github.event_name }}"
        
